name: py3p5_qt4
channels:
  - defaults
dependencies:
  - bitarray=0.8.1
  - comtypes=1.1.4
  - jsonschema=2.6.0
  - matplotlib=1.5.1
  - numpy=1.11.3
  - numpy-base=1.14.3
  - pandas=0.23.0
  - pillow=3.4.2
  - pip=19.0.3
  - pyqt=4.11.4
  - pytables=3.4.3
  - python=3.5.5
  - pywin32=223
  - pyzmq=17.0.0
  - qt=4.8.7
  - scipy=1.1.0
  - sphinx=1.7.9
  - sphinx_rtd_theme=0.4.3
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - xlwt=1.3.0
  - pip:
    - sphinxcontrib-programoutput==0.13
    - sphinxcontrib-programscreenshot==0.0.0
    - watchdog==0.9.0
    - prettyplotlib==0.1.7
    - py2exe==0.9.2.2 