# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LeashMW.ui'
#
# Created: Tue Sep 16 16:34:24 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(886, 659)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_Setup = QtGui.QWidget()
        self.tab_Setup.setObjectName(_fromUtf8("tab_Setup"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_Setup)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.tab_Setup)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.treeWidgetCal = QtGui.QTreeWidget(self.groupBox)
        self.treeWidgetCal.setObjectName(_fromUtf8("treeWidgetCal"))
        self.treeWidgetCal.headerItem().setText(0, _fromUtf8("Calibration"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetCal)
        item_0.setToolTip(0, _fromUtf8(""))
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetCal)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidgetCal)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        self.horizontalLayout_2.addWidget(self.treeWidgetCal)
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButtonLoadMask = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonLoadMask.setObjectName(_fromUtf8("pushButtonLoadMask"))
        self.horizontalLayout.addWidget(self.pushButtonLoadMask)
        self.toolButtonRescale = QtGui.QToolButton(self.groupBox_5)
        self.toolButtonRescale.setObjectName(_fromUtf8("toolButtonRescale"))
        self.horizontalLayout.addWidget(self.toolButtonRescale)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.graphicsViewMask = QtGui.QGraphicsView(self.groupBox_5)
        self.graphicsViewMask.setObjectName(_fromUtf8("graphicsViewMask"))
        self.verticalLayout_2.addWidget(self.graphicsViewMask)
        self.horizontalLayout_10.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab_Setup)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_userdir = QtGui.QLabel(self.groupBox_2)
        self.label_userdir.setObjectName(_fromUtf8("label_userdir"))
        self.gridLayout_2.addWidget(self.label_userdir, 0, 0, 1, 1)
        self.lineEditExpDir = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditExpDir.setObjectName(_fromUtf8("lineEditExpDir"))
        self.gridLayout_2.addWidget(self.lineEditExpDir, 1, 1, 1, 1)
        self.lineEditUserDir = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditUserDir.setObjectName(_fromUtf8("lineEditUserDir"))
        self.gridLayout_2.addWidget(self.lineEditUserDir, 0, 1, 1, 1)
        self.lineEditSetupDir = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditSetupDir.setObjectName(_fromUtf8("lineEditSetupDir"))
        self.gridLayout_2.addWidget(self.lineEditSetupDir, 2, 1, 1, 1)
        self.label_Setupdir = QtGui.QLabel(self.groupBox_2)
        self.label_Setupdir.setObjectName(_fromUtf8("label_Setupdir"))
        self.gridLayout_2.addWidget(self.label_Setupdir, 2, 0, 1, 1)
        self.label_Exdir = QtGui.QLabel(self.groupBox_2)
        self.label_Exdir.setObjectName(_fromUtf8("label_Exdir"))
        self.gridLayout_2.addWidget(self.label_Exdir, 1, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.pushButtonnew = QtGui.QPushButton(self.tab_Setup)
        self.pushButtonnew.setObjectName(_fromUtf8("pushButtonnew"))
        self.verticalLayout_7.addWidget(self.pushButtonnew)
        self.tabWidget.addTab(self.tab_Setup, _fromUtf8(""))
        self.tab_Plot = QtGui.QWidget()
        self.tab_Plot.setObjectName(_fromUtf8("tab_Plot"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_Plot)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_Plot)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_11.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.groupBox_6)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab_Plot, _fromUtf8(""))
        self.tabHistory = QtGui.QWidget()
        self.tabHistory.setObjectName(_fromUtf8("tabHistory"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.tabHistory)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_4 = QtGui.QGroupBox(self.tabHistory)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(self.tabHistory)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_TotFiles = QtGui.QLabel(self.groupBox_3)
        self.label_TotFiles.setObjectName(_fromUtf8("label_TotFiles"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_TotFiles)
        self.label_Rate = QtGui.QLabel(self.groupBox_3)
        self.label_Rate.setObjectName(_fromUtf8("label_Rate"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Rate)
        self.lcdNumberFiles = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumberFiles.setObjectName(_fromUtf8("lcdNumberFiles"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lcdNumberFiles)
        self.lcdNumberRate = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumberRate.setObjectName(_fromUtf8("lcdNumberRate"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lcdNumberRate)
        self.horizontalLayout_8.addLayout(self.formLayout)
        self.verticalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_7 = QtGui.QGroupBox(self.tabHistory)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.textBrowserLogs = QtGui.QTextBrowser(self.groupBox_7)
        self.textBrowserLogs.setObjectName(_fromUtf8("textBrowserLogs"))
        self.verticalLayout_6.addWidget(self.textBrowserLogs)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.verticalLayout_4.addWidget(self.groupBox_7)
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.tabWidget.addTab(self.tabHistory, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 886, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuSAXS_Leash = QtGui.QMenu(self.menuBar)
        self.menuSAXS_Leash.setObjectName(_fromUtf8("menuSAXS_Leash"))
        self.menuQueue = QtGui.QMenu(self.menuBar)
        self.menuQueue.setObjectName(_fromUtf8("menuQueue"))
        self.menuHelp = QtGui.QMenu(self.menuBar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionLoad_Calibration = QtGui.QAction(MainWindow)
        self.actionLoad_Calibration.setObjectName(_fromUtf8("actionLoad_Calibration"))
        self.actionImport = QtGui.QAction(MainWindow)
        self.actionImport.setObjectName(_fromUtf8("actionImport"))
        self.actionClose_Queue = QtGui.QAction(MainWindow)
        self.actionClose_Queue.setObjectName(_fromUtf8("actionClose_Queue"))
        self.actionAbort_Queue = QtGui.QAction(MainWindow)
        self.actionAbort_Queue.setObjectName(_fromUtf8("actionAbort_Queue"))
        self.actionSave_Calibration = QtGui.QAction(MainWindow)
        self.actionSave_Calibration.setObjectName(_fromUtf8("actionSave_Calibration"))
        self.actionRecent_Files = QtGui.QAction(MainWindow)
        self.actionRecent_Files.setObjectName(_fromUtf8("actionRecent_Files"))
        self.actionSave_Calibration_as = QtGui.QAction(MainWindow)
        self.actionSave_Calibration_as.setObjectName(_fromUtf8("actionSave_Calibration_as"))
        self.actionOpen_Hep_in_Browser = QtGui.QAction(MainWindow)
        self.actionOpen_Hep_in_Browser.setObjectName(_fromUtf8("actionOpen_Hep_in_Browser"))
        self.actionShow_Server_Configuration = QtGui.QAction(MainWindow)
        self.actionShow_Server_Configuration.setObjectName(_fromUtf8("actionShow_Server_Configuration"))
        self.actionNew_Calibration = QtGui.QAction(MainWindow)
        self.actionNew_Calibration.setObjectName(_fromUtf8("actionNew_Calibration"))
        self.action_Reread_Directory = QtGui.QAction(MainWindow)
        self.action_Reread_Directory.setObjectName(_fromUtf8("action_Reread_Directory"))
        self.menuSAXS_Leash.addAction(self.actionLoad_Calibration)
        self.menuSAXS_Leash.addAction(self.actionNew_Calibration)
        self.menuSAXS_Leash.addAction(self.actionImport)
        self.menuSAXS_Leash.addAction(self.actionSave_Calibration)
        self.menuSAXS_Leash.addAction(self.actionSave_Calibration_as)
        self.menuSAXS_Leash.addSeparator()
        self.menuQueue.addAction(self.actionClose_Queue)
        self.menuQueue.addAction(self.actionAbort_Queue)
        self.menuQueue.addAction(self.actionShow_Server_Configuration)
        self.menuQueue.addAction(self.action_Reread_Directory)
        self.menuHelp.addAction(self.actionOpen_Hep_in_Browser)
        self.menuBar.addAction(self.menuSAXS_Leash.menuAction())
        self.menuBar.addAction(self.menuQueue.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Saxs Leash", None))
        self.groupBox.setTitle(_translate("MainWindow", "Setup", None))
        self.treeWidgetCal.headerItem().setText(1, _translate("MainWindow", "Value", None))
        self.treeWidgetCal.headerItem().setText(2, _translate("MainWindow", "Units", None))
        __sortingEnabled = self.treeWidgetCal.isSortingEnabled()
        self.treeWidgetCal.setSortingEnabled(False)
        self.treeWidgetCal.topLevelItem(0).setText(0, _translate("MainWindow", "Wavelength:", None))
        self.treeWidgetCal.topLevelItem(0).setText(1, _translate("MainWindow", "jjbf", None))
        self.treeWidgetCal.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "1.5", None))
        self.treeWidgetCal.topLevelItem(1).setText(0, _translate("MainWindow", "sdas", None))
        self.treeWidgetCal.topLevelItem(1).child(0).setText(0, _translate("MainWindow", "293", None))
        self.treeWidgetCal.topLevelItem(1).child(1).setText(0, _translate("MainWindow", "343", None))
        self.treeWidgetCal.topLevelItem(2).setText(0, _translate("MainWindow", "Tilt", None))
        self.treeWidgetCal.topLevelItem(2).child(0).setText(0, _translate("MainWindow", "TiltAngle", None))
        self.treeWidgetCal.topLevelItem(2).child(0).child(0).setText(0, _translate("MainWindow", "3", None))
        self.treeWidgetCal.topLevelItem(2).child(1).setText(0, _translate("MainWindow", "TiltRot", None))
        self.treeWidgetCal.topLevelItem(2).child(1).child(0).setText(0, _translate("MainWindow", "34", None))
        self.treeWidgetCal.setSortingEnabled(__sortingEnabled)
        self.groupBox_5.setTitle(_translate("MainWindow", "Maskfile", None))
        self.pushButtonLoadMask.setText(_translate("MainWindow", "Load Maskfile", None))
        self.toolButtonRescale.setText(_translate("MainWindow", "Rescale", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Directory", None))
        self.label_userdir.setText(_translate("MainWindow", "User:", None))
        self.label_Setupdir.setText(_translate("MainWindow", "Setup:", None))
        self.label_Exdir.setText(_translate("MainWindow", "Experiment:    ", None))
        self.pushButtonnew.setText(_translate("MainWindow", "Start Server Queue with this Calibration", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Setup), _translate("MainWindow", "Setup", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Diffraction Curve", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Plot), _translate("MainWindow", "Plot", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Images Processed", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Meters", None))
        self.label_TotFiles.setText(_translate("MainWindow", "Files Processed", None))
        self.label_Rate.setText(_translate("MainWindow", "Current rate", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Logs", None))
        self.textBrowserLogs.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHistory), _translate("MainWindow", "History", None))
        self.menuSAXS_Leash.setTitle(_translate("MainWindow", "&File", None))
        self.menuQueue.setTitle(_translate("MainWindow", "Q&ueue", None))
        self.menuHelp.setTitle(_translate("MainWindow", "&Help", None))
        self.actionLoad_Calibration.setText(_translate("MainWindow", "&Open Calibration", None))
        self.actionImport.setText(_translate("MainWindow", "&Import Calibration", None))
        self.actionClose_Queue.setText(_translate("MainWindow", "&Close Queue", None))
        self.actionAbort_Queue.setText(_translate("MainWindow", "&Abort Queue", None))
        self.actionSave_Calibration.setText(_translate("MainWindow", "&Save Calibration", None))
        self.actionRecent_Files.setText(_translate("MainWindow", "Recent Files", None))
        self.actionSave_Calibration_as.setText(_translate("MainWindow", "Save Calibration &as", None))
        self.actionOpen_Hep_in_Browser.setText(_translate("MainWindow", "&Open Hep in Browser", None))
        self.actionShow_Server_Configuration.setText(_translate("MainWindow", "Show Server Configuration", None))
        self.actionNew_Calibration.setText(_translate("MainWindow", "&New Calibration", None))
        self.action_Reread_Directory.setText(_translate("MainWindow", "&Reread Directory", None))

